name: Documentation Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repostiory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Docs Distributable Folder
        run: mkdir output
      
      - name: Generate PDF for Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: docs/src/documentation.md -o output/documentation.pdf --template eisvogel --listings

      - name: Generate PDF for Specification
        uses: docker://pandoc/extra:latest
        with:
          args: docs/src/specification.md -o output/specification.pdf --template eisvogel --listings

      - name: Generate PDF for Testing
        uses: docker://pandoc/extra:latest
        with:
          args: docs/src/testing.md -o output/testing.pdf --template eisvogel --listings

      - name: Generate PDF for Whitepaper
        uses: docker://pandoc/extra:latest
        with:
          args: docs/src/whitepaper.md -o output/whitepaper.pdf --template eisvogel --listings
      
      - name: Upload Generated Documentation Files
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: output