name: Documentation Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repostiory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Fetch Markdown Files From Docs
        id: docs_list
        run: |
          cd docs/src
          files=$(printf "docs/src/%s " *.md)
          echo "files=$files" > $GITHUB_OUTPUT

      - name: Generate Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --output=docs/dist/result.pdf ${{ steps.docs_list.outputs.files }}
      
      - name: Upload Generated Documentation Files
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs