name: Documentation Release

on:
  pull_request:
    branches: [ "main" ]
    paths: ['docs/src/**']

  workflow_dispatch:

jobs:
  gen_docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Clean Documentation Dist Folder
        run: |
          rm -rf docs/dist
          mkdir docs/dist
      - name: DocGen - Programming Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/documentation.pdf "docs/src/documentation.md"

      - name: DocGen - Specification Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/specification.pdf "docs/src/specification.md"
            
      - name: DocGen - Testing Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/testing.pdf "docs/src/testing.md"

      - name: DocGen - Whitepaper Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/whitepaper.pdf "docs/src/whitepaper.md"

      - name: DocGen - Development Environment Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/development_environment.pdf "docs/src/development_environment.md"

      - name: DocGen - Language Architecture Document
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/interpreter_architecture.pdf "docs/src/interpreter_architecture.md"

      - name: DocGen - Post Mortem
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/post_mortem.pdf "docs/src/post_mortem.md"

      - name: Upload Generated Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/dist/*

      - name: Git Commit Generated Documentation Artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Documentation Artifacts
          file_pattern: '*.pdf'
